version: '3.8'
services:
  backend:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:rw #(Bind mount) shink from local to docker, ro-->read only
      - ./Upload/images:/usr/src/app/Upload/images:rw
    # env_file:
    #   - ./app/core/.env
    command: bash -c "printenv && alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

    depends_on:
      - postgres
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 5501:80
    volumes:
    - ./client:/usr/share/nginx/html 
    # - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - backend
    networks:
    - app-network
  
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD} 
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME} 
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network
volumes:
  postgres-db:

networks:
  app-network:
    driver: bridge

